#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

get_news_car:
    path: news/car
    controller: App\Controller\NewsCarController
    methods: GET
